/*
 * File: CarMasterDetail.ui.js
 * Date: Mon Apr 12 2010 22:46:29 GMT-0700 (PDT)
 * 
 * This file was generated by Ext Designer version xds-1.0.0.7c.
 * http://www.sencha.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

CarMasterDetailUi = Ext.extend(Ext.Panel, {
    title: 'Grid',
    width: 565,
    height: 400,
    layout: 'vbox',
    frame: true,
    initComponent: function() {
        this.layoutConfig = {
            align: 'stretch'
        };
        this.items = [
            {
                xtype: 'grid',
                title: 'My Grid',
                store: 'MyStore',
                flex: 1,
                header: false,
                viewConfig: {
                    forceFit: true
                },
                ref: 'grid',
                columns: [
                    {
                        xtype: 'gridcolumn',
                        header: 'Manufacturer',
                        sortable: true,
                        resizable: true,
                        width: 100,
                        dataIndex: 'manufacturer'
                    },
                    {
                        xtype: 'gridcolumn',
                        header: 'Model',
                        sortable: true,
                        resizable: true,
                        width: 100,
                        dataIndex: 'model'
                    },
                    {
                        xtype: 'numbercolumn',
                        header: 'Price',
                        sortable: true,
                        resizable: true,
                        width: 100,
                        format: '$0,000.00',
                        align: 'right',
                        dataIndex: 'price'
                    }
                ]
            },
            {
                xtype: 'panel',
                flex: 1,
                tpl: [
                    '<img src="cars/{img}" style="float: right" />',
                    'Manufacturer: {manufacturer}<br/>',
                    'Model: <a href="{wiki}" target="_blank">{model}</a><br/>',
                    'Price: {price:usMoney}<br/>'
                ],
                padding: 7,
                ref: 'detail'
            }
        ];
        CarMasterDetailUi.superclass.initComponent.call(this);
    }
});
