/*
 * File: xds_index.js
 * Date: Mon Apr 12 2010 22:46:29 GMT-0700 (PDT)
 * 
 * This file was generated by Ext Designer version xds-1.0.0.7c.
 * http://www.sencha.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

Ext.onReady(function() {
    var carMasterDetail = new CarMasterDetail({
        renderTo: Ext.getBody()
    });
    carMasterDetail.show();
});
